# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-06 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('forename', models.CharField(blank=True, max_length=32)),
                ('surname', models.CharField(blank=True, max_length=32)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('occupation', models.CharField(blank=True, max_length=32)),
                ('zipcode', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
