# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_remove_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('year', models.IntegerField(blank=True, default=0)),
                ('imageURL', models.CharField(blank=True, max_length=256)),
                ('isAction', models.BooleanField(default=False)),
                ('isAdventure', models.BooleanField(default=False)),
                ('isAnimation', models.BooleanField(default=False)),
                ('isChildrens', models.BooleanField(default=False)),
                ('isComedy', models.BooleanField(default=False)),
                ('isCrime', models.BooleanField(default=False)),
                ('isDocumentary', models.BooleanField(default=False)),
                ('isDrama', models.BooleanField(default=False)),
                ('isFantasy', models.BooleanField(default=False)),
                ('isFilmNoir', models.BooleanField(default=False)),
                ('isHorror', models.BooleanField(default=False)),
                ('isMusical', models.BooleanField(default=False)),
                ('isMystery', models.BooleanField(default=False)),
                ('isRomance', models.BooleanField(default=False)),
                ('isSciFi', models.BooleanField(default=False)),
                ('isThriller', models.BooleanField(default=False)),
                ('isWar', models.BooleanField(default=False)),
                ('isWestern', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
