# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_movies_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_id',
            field=models.IntegerField(default=0),
        ),
    ]
