# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_movies_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isAction',
            new_name='is_action',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isAdventure',
            new_name='is_adventure',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isAnimation',
            new_name='is_animation',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isChildrens',
            new_name='is_childrens',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isComedy',
            new_name='is_comedy',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isCrime',
            new_name='is_crime',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isDocumentary',
            new_name='is_documentary',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isDrama',
            new_name='is_drama',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isFantasy',
            new_name='is_fantasy',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isFilmNoir',
            new_name='is_filmnoir',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isHorror',
            new_name='is_horror',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isMusical',
            new_name='is_musical',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isMystery',
            new_name='is_mystery',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isRomance',
            new_name='is_romance',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isSciFi',
            new_name='is_scifi',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isThriller',
            new_name='is_thriller',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isWar',
            new_name='is_war',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='isWestern',
            new_name='is_western',
        ),
    ]
