# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-29 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_auto_20190109_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='timestamp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
