# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0008_auto_20190501_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizemodel',
            name='model_sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
